FROM mcr.microsoft.com/dotnet/sdk:10.0

WORKDIR /src

COPY CloudCart.Api/CloudCart.Api.csproj CloudCart.Api/
RUN dotnet restore CloudCart.Api/CloudCart.Api.csproj

COPY CloudCart.Api/ CloudCart.Api/

WORKDIR /src/CloudCart.Api

RUN dotnet tool install --global dotnet-ef

ENV PATH="$PATH:/root/.dotnet/tools"

ENTRYPOINT ["dotnet", "ef", "database", "update"]